export interface JobData {
  id: string
  companyName: string
  jobTitle: string
  salary: string
  location: string
  companyScale: string
  industry: string
  education: string
  experience: string
  aiScore: number
  bgScore: number
  skillScore: number
  expScore: number
  skillReq: string
  hrActivity: string
  followStatus: string
  captureTime: string
  applyDate: string
  myReview: string
  workAddress: string
  hrSkills: string[]
  benefits: string[]
  jobDescription: string
  directLink: string
  aiRewriteJson: string
  manualRefinedResume: string
  dreamPicture: string
  atsAbilityAnalysis: string
  resumeAudit: string
  strongFitAssessment: string
  riskRedFlags: string
  deepActionPlan: string
  // 🌟 方案A：5 个诊断字段的全量合成版（后端 normalize_job_record 已拼接），供多Agent重构等全视野场景取用。
  // 各按钮的精准喂料（方案B）请直接取上面的原子字段，避免重复消费全量 token。
  compositeDiagnosisReport: string
  greetingMsg: string
  secondQaReport: string
  platform: string
  role: string
  publishDate: string
  preliminaryScore: number
  bonusWords: string
  deductionWords: string
  grade: string
  roleMatch: number
  skillsAlign: number
  seniority: number
  compensation: number
  interviewProb: number
  companyStage: number
  marketFit: number
  growth: number
  aiEvaluationDetail: string
  companyIntel?: string
  predictedQa?: string
  jdText?: string
  evaluationReport?: string
  latestResumeText?: string
  qaReport?: string
  live_interview_record?: string
  resume_qa?: string
  amapLink?: string
  interviewReport?: string
  multiAgentRewrite?: string
  interviewTime?: string
  interviewLocation?: string
}
